"""add_attachments_to_messages

Revision ID: ace134487c31
Revises: b10770b04cbb
Create Date: 2026-06-19 14:38:14.578994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace134487c31'
down_revision: Union[str, None] = 'b10770b04cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_messages', sa.Column('attachment_url', sa.String(), nullable=True))
    op.add_column('group_messages', sa.Column('attachment_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_messages', 'attachment_type')
    op.drop_column('group_messages', 'attachment_url')
    # ### end Alembic commands ###
